home:
  alias: '/blog'

pages:
  theme: soraarticle
  process:
    markdown: true
    twig: false
  markdown:
    extra: true

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: false
  auto_reload: false
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: false
  twig: false
  shutdown:
    close_connection: true
